/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewRouteImport } from './routes/new'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryStoryIdRouteImport } from './routes/story.$storyId'
import { Route as ApiPublicHooksAiContinueRouteImport } from './routes/api/public/hooks/ai-continue'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAiContinueRoute =
  ApiPublicHooksAiContinueRouteImport.update({
    id: '/api/public/hooks/ai-continue',
    path: '/api/public/hooks/ai-continue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/api/public/hooks/ai-continue': typeof ApiPublicHooksAiContinueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/api/public/hooks/ai-continue': typeof ApiPublicHooksAiContinueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/story/$storyId': typeof StoryStoryIdRoute
  '/api/public/hooks/ai-continue': typeof ApiPublicHooksAiContinueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/new'
    | '/profile'
    | '/story/$storyId'
    | '/api/public/hooks/ai-continue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/new'
    | '/profile'
    | '/story/$storyId'
    | '/api/public/hooks/ai-continue'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/new'
    | '/profile'
    | '/story/$storyId'
    | '/api/public/hooks/ai-continue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
  ApiPublicHooksAiContinueRoute: typeof ApiPublicHooksAiContinueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-continue': {
      id: '/api/public/hooks/ai-continue'
      path: '/api/public/hooks/ai-continue'
      fullPath: '/api/public/hooks/ai-continue'
      preLoaderRoute: typeof ApiPublicHooksAiContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
  ApiPublicHooksAiContinueRoute: ApiPublicHooksAiContinueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
