/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryStoryIdRouteImport } from './routes/story.$storyId'
import { Route as StoryStoryIdWriteRouteImport } from './routes/story.$storyId.write'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdWriteRoute = StoryStoryIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => StoryStoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/story/$storyId/write': typeof StoryStoryIdWriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/story/$storyId/write': typeof StoryStoryIdWriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/story/$storyId/write': typeof StoryStoryIdWriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/new'
    | '/story/$storyId'
    | '/story/$storyId/write'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/new' | '/story/$storyId' | '/story/$storyId/write'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/new'
    | '/story/$storyId'
    | '/story/$storyId/write'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewRoute: typeof NewRoute
  StoryStoryIdRoute: typeof StoryStoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId/write': {
      id: '/story/$storyId/write'
      path: '/write'
      fullPath: '/story/$storyId/write'
      preLoaderRoute: typeof StoryStoryIdWriteRouteImport
      parentRoute: typeof StoryStoryIdRoute
    }
  }
}

interface StoryStoryIdRouteChildren {
  StoryStoryIdWriteRoute: typeof StoryStoryIdWriteRoute
}

const StoryStoryIdRouteChildren: StoryStoryIdRouteChildren = {
  StoryStoryIdWriteRoute: StoryStoryIdWriteRoute,
}

const StoryStoryIdRouteWithChildren = StoryStoryIdRoute._addFileChildren(
  StoryStoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewRoute: NewRoute,
  StoryStoryIdRoute: StoryStoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
